---
tags: []
projects: [spring-framework]
---
:spring_version: current
:spring_boot_version: 1.3.3.RELEASE
:Component: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/stereotype/Component.html
:Controller: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/stereotype/Controller.html
:DispatcherServlet: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/web/servlet/DispatcherServlet.html
:SpringApplication: http://docs.spring.io/spring-boot/docs/{spring_boot_version}/api/org/springframework/boot/SpringApplication.html
:ResponseBody: http://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/web/bind/annotation/ResponseBody.html
:SpringBootApplication: http://docs.spring.io/spring-boot/docs/{spring_boot_version}/api/org/springframework/boot/autoconfigure/SpringBootApplication.html
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-uploading-files
This guide walks you through the process of creating a server application that can receive multi-part file uploads.

== What you'll build

You will create a Spring MVC application that accepts file uploads. You will also build a simple client to upload a test file.


== What you'll need

:java_version: 1.8
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]
 

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]


include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-gradle.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-maven.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-sts.adoc[]



[[initial]]
== Create a configuration class

To upload files with Servlet 3.0 containers, you need to register a `MultipartConfigElement` class (which would be `<multipart-config>` in web.xml). Thanks to Spring Boot, that bean is already registered and available! All you need to get started with this application is the following, empty configuration setup.

`src/main/java/hello/Application.java`
[source,java]
----
include::initial/src/main/java/hello/Application.java[]
----

You will soon add a Spring MVC controller, which is why you need `@SpringBootApplication`. Spring Boot automatically finds `@Controller`-marked classes and registers them with the application context.

As part of auto-configuring Spring MVC, Spring Boot will create a `MultipartConfigElement` bean and make itself ready for file uploads.

NOTE: http://tomcat.apache.org/tomcat-7.0-doc/servletapi/javax/servlet/MultipartConfigElement.html[MultipartConfigElement] is a Servlet 3.0 standard element that defines the limits on uploading files. This component is supported by all compliant containers like Tomcat and Jetty. Later on in this guide, we'll see how to configure its limits.


== Create a file upload controller

In Spring MVC, a controller is used to handle file upload requests. The following code provides the web app with the ability to upload files.

`src/main/java/hello/FileUploadController.java`
[source,java]
----
include::complete/src/main/java/hello/FileUploadController.java[]
----

The entire class is marked up with `@Controller` so Spring MVC can pick it up and look for routes.

Each method is tagged with `@RequestMapping` to flag the path and the HTTP action. In this case, `GET` looks up the current list of uploaded files (stored in `Application.ROOT` folder) and load it into a Thymeleaf template.

NOTE: This example uses Java 8's streams support to transform an array of `java.io.File` objects into a sorted list of filenames (latest to earliest modified timestamp).


The `handleFileUpload` method is geared to handle a two-part message: `name` and `file`. It checks to make sure the file name contains no illegal characers, and then copies the bytes into a target file through a `BufferedOutputStream`.

NOTE: In a production scenario, you more likely would store the files in a temporary location, a database, or perhaps a NoSQL store like http://docs.mongodb.org/manual/core/gridfs[Mongo's GridFS]. It's is best to NOT load up the file system of your application with content.

WARNING: This code has some rudimentary checks to avoid files escaping the file system, but doesnt' protect against people uploading executables, etc. which could be used to launch attacks.

== Creating a barebones template

To build something of interest, the following Thymeleaf template is a nice example of uploading files as well as showing what's been uploaded.

`src/main/resources/templates/uploadForm.html`
[source,xml]
----
include::complete/src/main/resources/templates/uploadForm.html[]
----

This template has three parts:

* An optional message at the top where Spring MVC writes a http://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#mvc-flash-attributes[flash-scoped messages].
* A form allowing the user to upload files
* A list of files supplied from the backend


== Tuning file upload limits

When configuring file uploads, it is often useful to set limits on the size of files. Imagine trying to handle a 5GB file upload! With Spring Boot, we can configure its auto-configured `MultipartConfigElement` with some property settings.

Create `src/main/resources/application.properties` and make it look like this:

`src/main/resources/application.properties`
[source,java]
----
include::complete/src/main/resources/application.properties[]
----

The multipart settings are constrained as follows:

* `multipart.maxFileSize` is set to 128KB, meaning total file size cannot exceed 128KB.
* `multipart.maxRequestSize` is set to 128KB, meaning total request size for a `multipart/form-data` cannot exceed 128KB.

== Make the application executable

Although it is possible to package this service as a traditional link:/understanding/WAR[WAR] file for deployment to an external application server, the simpler approach demonstrated below creates a _standalone application_. You package everything in a single, executable JAR file, driven by a good old Java `main()` method. And along the way, you use Spring's support for embedding the link:/understanding/Tomcat[Tomcat] servlet container as the HTTP runtime, instead of deploying to an external instance.


`src/main/java/hello/Application.java`
[source,java]
----
include::complete/src/main/java/hello/Application.java[]
----

`@SpringBootApplication` is a convenience annotation that adds all of the following:
    
- `@Configuration` tags the class as a source of bean definitions for the application context.
- `@EnableAutoConfiguration` tells Spring Boot to start adding beans based on classpath settings, other beans, and various property settings.
- Normally you would add `@EnableWebMvc` for a Spring MVC app, but Spring Boot adds it automatically when it sees **spring-webmvc** on the classpath. This flags the application as a web application and activates key behaviors such as setting up a `DispatcherServlet`.
- `@ComponentScan` tells Spring to look for other components, configurations, and services in the the `hello` package, allowing it to find the `FileUploadController`.

The `main()` method uses Spring Boot's `SpringApplication.run()` method to launch an application. Did you notice that there wasn't a single line of XML? No **web.xml** file either. This web application is 100% pure Java and you didn't have to deal with configuring any plumbing or infrastructure.

You also want a target folder to upload files to, so there is a Java 8 lambda used to create a Boot `CommandLineRunner` at startup which creates that folder.


include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_subhead.adoc[]
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_with_both.adoc[]


That runs the server-side piece that receives file uploads. Logging output is displayed. The service should be up and running within a few seconds.

With the server running, you need to open a browser and visit http://localhost:8080/upload to see the upload form. Pick a (small) file and press "Upload" and you should see the success page from the controller. Choose a file that is too large and you will get an ugly error page.

You should then see something like this in your browser window:

....
You successfully uploaded <name of your file>!
....


== Summary

Congratulations! You have just written a web application that uses Spring to handle file uploads.


include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/footer.adoc[]

