:spring_version: current
:spring_boot_version: 3.1.0
:Controller: https://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/stereotype/Controller.html
:SpringApplication: https://docs.spring.io/spring-boot/docs/{spring_boot_version}/api/org/springframework/boot/SpringApplication.html
:ResponseBody: https://docs.spring.io/spring/docs/{spring_version}/javadoc-api/org/springframework/web/bind/annotation/ResponseBody.html
:SpringBootApplication: https://docs.spring.io/spring-boot/docs/{spring_boot_version}/api/org/springframework/boot/autoconfigure/SpringBootApplication.html
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-uploading-files

This guide walks you through the process of creating a server application that can receive
HTTP multi-part file uploads.

== What You Will Build

You will create a Spring Boot web application that accepts file uploads. You will also
build a simple HTML interface to upload a test file.

== What You Need

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/prereq_editor_jdk_buildtools.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/how_to_complete_this_guide.adoc[]

[[scratch]]
== Starting with Spring Initializr

You can use this https://start.spring.io/#!type=maven-project&groupId=com.example&artifactId=uploading-files&name=uploading-files&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.uploading-files&dependencies=web,thymeleaf[pre-initialized project] and click Generate to download a ZIP file. This project is configured to fit the examples in this tutorial.

To manually initialize the project:

. Navigate to https://start.spring.io.
This service pulls in all the dependencies you need for an application and does most of the setup for you.
. Choose either Gradle or Maven and the language you want to use. This guide assumes that you chose Java.
. Click *Dependencies* and select *Spring Web* and *Thymeleaf*.
. Click *Generate*.
. Download the resulting ZIP file, which is an archive of a web application that is configured with your choices.

NOTE: If your IDE has the Spring Initializr integration, you can complete this process from your IDE.

NOTE: You can also fork the project from Github and open it in your IDE or other editor.

[[initial]]
== Create an Application Class

To start a Spring Boot MVC application, you first need a starter. In this sample,
`spring-boot-starter-thymeleaf` and `spring-boot-starter-web` are already added as
dependencies. To upload files with Servlet containers, you need to register a
`MultipartConfigElement` class (which would be `<multipart-config>` in web.xml). Thanks to
Spring Boot, everything is auto-configured for you!

All you need to get started with this application is the following
`UploadingFilesApplication` class (from
`src/main/java/com/example/uploadingfiles/UploadingFilesApplication.java`):

====
[source,java]
----
include::initial/src/main/java/com/example/uploadingfiles/UploadingFilesApplication.java[]
----
====

As part of auto-configuring Spring MVC, Spring Boot will create a `MultipartConfigElement`
bean and make itself ready for file uploads.

== Create a File Upload Controller

The initial application already contains a few classes to deal with storing and loading
the uploaded files on disk. They are all located in the
`com.example.uploadingfiles.storage` package. You will use those in your new
`FileUploadController`. The following listing (from
`src/main/java/com/example/uploadingfiles/FileUploadController.java`) shows the file
upload controller:

====
[source,java]
----
include::complete/src/main/java/com/example/uploadingfiles/FileUploadController.java[]
----
====

The `FileUploadController` class is annotated with `@Controller` so that Spring MVC can
pick it up and look for routes. Each method is tagged with `@GetMapping` or `@PostMapping`
to tie the path and the HTTP action to a particular controller action.

In this case:

* `GET /`: Looks up the current list of uploaded files from the `StorageService` and loads
it into a Thymeleaf template. It calculates a link to the actual resource by using
`MvcUriComponentsBuilder`.
* `GET /files/{filename}`: Loads the resource (if it exists) and sends it to the browser
to download by using a `Content-Disposition` response header.
* `POST /`: Handles a multi-part message `file` and gives it to the `StorageService` for
saving.

NOTE: In a production scenario, you more likely would store the files in a temporary
location, a database, or perhaps a NoSQL store (such as
https://docs.mongodb.org/manual/core/gridfs[Mongo's GridFS]). It is best to NOT load up
the file system of your application with content.

You will need to provide a `StorageService` so that the controller can interact with a
storage layer (such as a file system). The following listing (from
`src/main/java/com/example/uploadingfiles/storage/StorageService.java`) shows that
interface:

====
[source,java]
----
include::complete/src/main/java/com/example/uploadingfiles//storage/StorageService.java[]
----
====

== Creating an HTML Template

The following Thymeleaf template (from `src/main/resources/templates/uploadForm.html`)
shows an example of how to upload files and show what has been uploaded:

====
[source,xml]
----
include::complete/src/main/resources/templates/uploadForm.html[]
----
====

This template has three parts:

* An optional message at the top where Spring MVC writes a
 https://docs.spring.io/spring/docs/current/spring-framework-reference/htmlsingle/#mvc-flash-attributes[flash-scoped message].
* A form that lets the user upload files.
* A list of files supplied from the backend.

== Tuning File Upload Limits

When configuring file uploads, it is often useful to set limits on the size of files.
Imagine trying to handle a 5GB file upload! With Spring Boot, we can tune its
auto-configured `MultipartConfigElement` with some property settings.

Add the following properties to your existing properties settings (in
`src/main/resources/application.properties`):

====
[source,java]
----
include::complete/src/main/resources/application.properties[]
----
====

The multipart settings are constrained as follows:

* `spring.servlet.multipart.max-file-size` is set to 128KB, meaning total file size cannot
exceed 128KB.
* `spring.servlet.multipart.max-request-size` is set to 128KB, meaning total request size for
a `multipart/form-data` cannot exceed 128KB.

== Run the Application

You want a target folder to which to upload files, so you need to enhance the basic
`UploadingFilesApplication` class that Spring Initializr created and add a Boot
`CommandLineRunner` to delete and re-create that folder at startup. The following listing
(from `src/main/java/com/example/uploadingfiles/UploadingFilesApplication.java`) shows how
to do so:

====
[source,java]
----
include::complete/src/main/java/com/example/uploadingfiles/UploadingFilesApplication.java[]
----
====

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/spring-boot-application-new-path.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/build_an_executable_jar_subhead.adoc[]
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/build_an_executable_jar_with_both.adoc[]

That runs the server-side piece that receives file uploads. Logging output is displayed.
The service should be up and running within a few seconds.

With the server running, you need to open a browser and visit `http://localhost:8080/` to
see the upload form. Pick a (small) file and press *Upload*. You should see the success
page from the controller. If you choose a file that is too large, you will get an ugly
error page.

You should then see a line resembling the following in your browser window:

"`You successfully uploaded <name of your file>!`"

== Testing Your Application

There are multiple ways to test this particular feature in our application. The following
listing (from `src/test/java/com/example/uploadingfiles/FileUploadTests.java`) shows one
example that uses `MockMvc` so that it does not require starting the servlet container:

====
[source,java]
----
include::complete/src/test/java/com/example/uploadingfiles/FileUploadTests.java[]
----
====

In those tests, you use various mocks to set up the interactions with your controller and
the `StorageService` but also with the Servlet container itself by using
`MockMultipartFile`.

For an example of an integration test, see the `FileUploadIntegrationTests` class (which
is in `src/test/java/com/example/uploadingfiles`).

== Summary

Congratulations! You have just written a web application that uses Spring to handle file
uploads.

== See Also

The following guides may also be helpful:

* https://spring.io/guides/gs/serving-web-content/[Serving Web Content with Spring MVC]
* https://spring.io/guides/gs/handling-form-submission/[Handling Form Submission]
* https://spring.io/guides/gs/securing-web/[Securing a Web Application]
* https://spring.io/guides/gs/spring-boot/[Building an Application with Spring Boot]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/main/footer.adoc[]
